### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by nVitius** [juliensobrier/browshot-php#5]
It would be nice if this was on Packagist. Unless there is a reason why it currently isn't?

Might also be a good idea to make a tag instead of relying on dev-master.

**Comment by juliensobrier** [comment]
@cordoval this module is to interact wit the Browshot API (https://browshot.com/), very different from browscap-php.

**Comment by cordoval** [comment]
oh i see thanks! it has been a long while since i needed this but it is always good to know things.

**Comment by juliensobrier** [comment]
Thank you, browshot is not on Packagist: https://packagist.org/packages/browshot-php/browshot

**Comment by cordoval** [comment]
I think you meant to say it is "now" instead of "not" thanks! Yeah welcome to the world of community. Thanks for your good work!
